mysql:
   dns: root:??????????tcp(127.0.0.1:3306)/hanye?charset=utf8mb4&parseTime=True&loc=Local
Auth:
  AccessSecret: 
  AccessExpire: 604800
  RefreshSecret: 
  RefreshExpire: 2592000
  RefreshAfter: 604800
# redis:
#   addr: "127.0.0.1:6379"
#   password : ""
#   DB: 0
#   PoolSize: 30
#   MinIdleConns: 30
